#!/usr/bin/env node
/**
 * Reads .md files from src/posts, extracts body content with gray-matter,
 * and writes src/data/postBodies.js so the blog always has content without
 * relying on Vite's ?raw or dynamic imports.
 * Run before build: node scripts/embed-posts.js
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const postsDir = join(root, 'src', 'posts');
const outPath = join(root, 'src', 'data', 'postBodies.js');

const postFiles = ['llm_start_chat_blog.md', 'physics-to-cs-journey.md'];
const bodies = {};

for (const file of postFiles) {
  const path = join(postsDir, file);
  try {
    const raw = readFileSync(path, 'utf-8');
    let content = '';
    let id = file.replace(/\.md$/, '').replace(/_/g, '-');
    try {
      const parsed = matter(raw);
      content = parsed.content ?? '';
      if (parsed.data?.id) id = parsed.data.id;
    } catch {
      // Fallback: content is everything after the first ---...---
      const match = raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n([\s\S]*)$/);
      content = match ? match[1].trim() : raw;
    }
    bodies[id] = content;
  } catch (err) {
    console.error(`Error processing ${file}:`, err.message);
  }
}

const out = `// Auto-generated by scripts/embed-posts.js – do not edit by hand
export const postBodies = ${JSON.stringify(bodies, null, 0)};
`;

writeFileSync(outPath, out, 'utf-8');
console.log('Wrote src/data/postBodies.js with', Object.keys(bodies).length, 'posts');
